version: '3.8'

services:
  web:
    build:
      context: ./web  # Dockerfileがあるフォルダを指定
    volumes:
      - ./web:/app  # ローカルのwebディレクトリをコンテナ内の/appにマウント
    ports:
      - "33000:3000"  # ホストとコンテナのポートを指定
    # environment:
    #   - PORT=33000  # ここで環境変数を指定

  api:
    build:
      context: ./api
    volumes:
      - ./api:/var/www
    ports:
      - "33001:80"
    depends_on:
      db:
        condition: service_healthy  # dbがヘルシーになるまで待つ
    environment:
      DB_HOST: db
      DB_DATABASE: project_tracker
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "33006:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "33002:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_PORT: 3306
